### ISSUE TITLE
do not store the predictions and the fold indices in the database

### ISSUE THREAD

**Issue by agramfort** [paris-saclay-cds/ramp-board#269]
storing the predictions in the database makes it huge and we store it on disk anyway in the submission folders. Let's not store it twice and let's keep it out of the DB to make it lighter.

and apparently the same applies to cv indices.

**Comment by kegl** [comment]
Yes. It is an old "feature" that was questionable from the beginning. I decided to store cv indices to make sure that they are fixed once the event is added. If we trust that get_cv in problem.py is deterministic and will not change for example due to version change, we can just call it any time we need the cv fold indices.

Storing predictions only on disk should also be quite easy: SubmissionOnCVFold has these two fields: full_train_y_pred and test_y_pred. I think simply rewriting them as properties that return the np array read from file will do the job.

**Comment by kegl** [comment]
@agramfort @glemaitre I found one of the issues

There is a query here: https://github.com/paris-saclay-cds/ramp-board/blob/1c2cfe7af486e57ee0d4fb017b5266bb8ad152e3/ramp-database/ramp_database/tools/submission.py#L442

It probably needs to load the cv folds of _all_ the submissions, not only of the one needed here, meaning that leaderboard update was quadratic in terms of number of submission. When there is a direct backlink in the db, no need to do a query, that's why we have those backlinks. I have a patch here https://github.com/paris-saclay-cds/ramp-board/pull/276/commits/7ffaff1767a277b61d75edd2a9e57d583f951694 and here https://github.com/paris-saclay-cds/ramp-board/pull/276/commits/9edf12ee8fb5571602f37ba41692864371ed90bf, feel free to cherry pick them if you need it urgently. 

This does not solve the underlying issue, we should still get the preds out of the db.

**Comment by kegl** [comment]
Anther remark: in our challenge the cv folds are tiny but the predictions are big, and we also have the same issue. This means that it's not related to cv fold size but prediction size.

Half a GB takes about 5min to handle after the submission is trained which is still too much. But at least the time is not accumulating now as the number of submissions grows.

**Comment by glemaitre** [comment]
The solution for this issues is actually waiting for being copy-pasted from here: https://github.com/paris-saclay-cds/ramp-board/issues/226

**Comment by glemaitre** [comment]
It is a work-around for not loading the predictions by accessing directly to the timing and score.

**Comment by kegl** [comment]
OK, I'm looking at it. 

In the meantime I also implemented a slight acceleration: when multiple submissions are processed in the dispatecher.update_database_results, we only update the leaderboard once (not for each processed submission). See https://github.com/paris-saclay-cds/ramp-board/blob/0ed32caa3c92d81c9e3f56890e184ca04b35f517/ramp-engine/ramp_engine/dispatcher.py#L199

**Comment by kegl** [comment]
@glemaitre I tried your second fix in  https://github.com/paris-saclay-cds/ramp-board/issues/226, it didn't work, I commented there.

The first fix is essentially what I did, am I right?

**Comment by kegl** [comment]
OK, done. The get_time was easy, get_scores not so much. Both work lightning fast now. https://github.com/paris-saclay-cds/ramp-board/pull/276/commits/c42d7ebc3f7dc59d18918f27a5a5be526e7e509c

**Comment by agramfort** [comment]
let's make a PR with the few commits we need to add to master when you have
time.
I assume tests will tell us if something broke

thx @kegl

>
