### ISSUE TITLE
BUG uncaught error when getting the output [AWS worker]

### ISSUE THREAD

**Issue by tomMoral** [paris-saclay-cds/ramp-board#487]
We got this failure when running an event on AWS. This is probably because we use spot-instance. The whole process should be more fault-proof.

```python-traceback
Traceback (most recent call last):
  File "/opt/miniconda3/bin/ramp-launch", line 8, in <module>
    sys.exit(start())
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/cli.py", line 122, in start
    main()
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/cli.py", line 90, in dispatcher
    disp.launch()
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/dispatcher.py", line 310, in launch
    self.collect_result(session)
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/dispatcher.py", line 220, in collect_result
    elif worker.status == 'running':
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/base.py", line 82, in status
    elif self._is_submission_finished():
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/aws/worker.py", line 130, in _is_submission_finished
    self.config, self.instance.id, self.submission)
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/aws/api.py", line 797, in _training_finished
    return not _has_screen(config, instance_id, submission_name)
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/aws/api.py", line 840, in _has_screen
    nb = int(_run(config, instance_id, cmd, return_output=True))
  File "/opt/miniconda3/lib/python3.7/site-packages/ramp_engine/aws/api.py", line 776, in _run
    return subprocess.check_output(cmd, shell=True)
  File "/opt/miniconda3/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/opt/miniconda3/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'ssh -o 'StrictHostKeyChecking no' -i /home/ramp/.ssh/aws_ramp_ireland.pem ubuntu@52.51.236.192 "screen -ls|awk '{print $1}' | cut -d. -f2 | grep submission_000005687| wc $│··························
l"' returned non-zero exit status 255.    
```

**Comment by lucyleeow** [comment]
So even though worker status is 'running' the instance is not working? Any idea why this is happening?

Spot instances should be launched properly due to:
```Python
waiter = client.get_waiter('spot_instance_request_fulfilled')
```
so my guess would be that after starting the instance stops for some reason?

In the AWS teardown I make sure the instance is running before I terminate it:
```Python
    def teardown(self):
        """Terminate the Amazon instance"""
        # Only terminate if instance is running
        instance_status = aws.check_instance_status(
            self.config, self.instance.id
        )
        if instance_status == 'running':
            aws.terminate_ec2_instance(self.config, self.instance.id)
        super().teardown()
```

as a fix, though not the best/ideal, we can check that the instance is running before we do the rest of the result collection?

**Comment by agramfort** [comment]
spot instances can be turned off without our action

can this be the reason of the failure?

>

**Comment by lucyleeow** [comment]
No - every time we check worker status we check if the spot has been terminated - I addressed the possibility of the instances being shut off at the start.
```Python
    @property
    def status(self):
        status = self._status
        if status == 'running':
            self._status_running_check_time = datetime.utcnow()
            if self._is_submission_interrupted():
                self._status = 'retry'
            elif self._is_submission_finished():
                self._status = 'finished'
        return self._status
```
`_is_submission_interrupted` checks if an instance has been marked to be terminated.

AWS people maybe know more about why instances are not working.

**Comment by tomMoral** [comment]
There is probably a race condition, no?

Can't you have an instance alive when you check `aws.check_instance_status` but it is killed before you call `aws.terminate_ec2_instance`?
With spot instances, all operation should be fault tolerant, and restart the submission if any "killed connection" is detected.

**Comment by lucyleeow** [comment]
@tomMoral you mean during teardown here?
```Python
    def teardown(self):
        """Terminate the Amazon instance"""
        # Only terminate if instance is running
        instance_status = aws.check_instance_status(
            self.config, self.instance.id
        )
        if instance_status == 'running':
            aws.terminate_ec2_instance(self.config, self.instance.id)
        super().teardown()
```
I mean it might be possible, but we do `aws.check_instance_status` right before killing it.

It wouldn't be the source of the error you put above though because that is occurring during a status check - at `_is_submission_finished`.
```Python
        if status == 'running':
            self._status_running_check_time = datetime.utcnow()
            if self._is_submission_interrupted():
                self._status = 'retry'
            elif self._is_submission_finished():
                self._status = 'finished'
```
the status of the working is 'running', then we use `_is_submission_interrupted` to check if the instance has been marked for termination by AWS and only if it hasn't do we check `_is_submission_finished`. But obviously the instance is not running - maybe it has been marked for termination and already terminated.

I can put a quick fix for this...

**Comment by maikia** [comment]
Hi All,
I agree with @tomMoral and @agramfort that because of the nature of the spot instances (ie that they might be killed at any point by AWS) we should be careful to catch the non-existant instance at any single point (even if we are just checked if it existed in any next time point it might not be the case anymore) and if it is no longer there we should restart the submission. 

I also agree with you @lucyleeow that it's good to make a additional checks but I don't think it will solve the above problem.

In the #491 I aim to address this problem. What do you think?

**Comment by lucyleeow** [comment]
I realise my PR wouldn't fix this error. During status check we first check if instance has been terminated (sends command - which does work) and then check if submission has been finished, right after, which fails. So supposedly the instance is killed very quickly. Which is odd because AWS says:
> When Amazon EC2 is going to interrupt your Spot Instance, it emits an event two minutes prior to the actual interruption

Either it is not sending it 2min before or some other reason causing the spot instance to not work. Either way the spot instance does not seem very robust.
ref: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html#interruption-behavior

**Comment by maikia** [comment]
> I realise my PR wouldn't fix this error. During status check we first check if instance has been terminated (sends command - which does work) and then check if submission has been finished, right after, which fails. So supposedly the instance is killed very quickly between the termination check and the sub finished check. Which is odd because AWS says:
> 
> > When Amazon EC2 is going to interrupt your Spot Instance, it emits an event two minutes prior to the actual interruption
> 
> Either it is not sending it 2min before or some other reason causing the spot instance to not work. Either way the spot instance does not seem very robust.
> ref: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html#interruption-behavior

hm. interesting @lucyleeow
Do you think that the `time_between_collection` set to > 2 mins could be a potential problem?

**Comment by lucyleeow** [comment]
I don't think so because it is failing when doing the status check:
```Python
    def status(self):
        status = self._status
        try:
            if status == 'running':
                self._status_running_check_time = datetime.utcnow()
                if self._is_submission_interrupted():
                    self._status = 'retry'
                elif self._is_submission_finished():
                    self._status = 'finished'
        except subprocess.CalledProcessError:
            # there was a problem while connecting to the worker
            # if you are using AWS it might be that an instance was terminated
            # from outside. retry the submission
            self._status = 'retry'
        return self._status
```
and there is not wait inside the status check...
